# Generated by Django 4.0.3 on 2022-10-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_name_customer_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autosale',
            old_name='sales_rep',
            new_name='sales_person',
        ),
    ]
