# Generated by Django 4.0.3 on 2022-10-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_rename_tech_technician'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='tech',
            new_name='technician',
        ),
    ]
