# Generated by Django 4.0.3 on 2022-10-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='automobile',
            new_name='vin',
        ),
    ]
