# Generated by Django 4.0.3 on 2022-10-26 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_rename_automobile_appointment_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='vin',
            new_name='automobile',
        ),
    ]
