# Generated by Django 4.0.3 on 2022-10-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='id',
            new_name='employee_number',
        ),
    ]
