# Generated by Django 4.0.3 on 2022-10-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0011_rename_id_technician_employee_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='employee_number',
            new_name='id',
        ),
    ]
