# Generated by Django 4.0.3 on 2022-10-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0012_rename_employee_number_technician_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='color',
        ),
        migrations.RemoveField(
            model_name='automobilevo',
            name='year',
        ),
    ]
